# Numpy 🎲
Studying the Numpy

by: Pedro Florencio

---

<b> How do I import?

In [43]:
import numpy as np

<b> How do I create an array?

In [44]:
lista = [1,2,3]

In [45]:
ar = np.array(lista)
ar

array([1, 2, 3])

<b> How do I create a matrix?

In [46]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [47]:
mat = np.array(matrix)
mat # It has 2 dimensions

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<b> How do I create a sequence of numbers (array)?

In [48]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

<b> How do I create an array of zeros?

In [50]:
np.zeros(3)

array([0., 0., 0.])

<b> How do I create a matrix of zeros?

In [51]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<b> How do I create a matrix of ones?

In [52]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

<b> How do I create an eye matrix?

In [53]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<b> How do I create a sequence with linspace?

In [54]:
np.linspace(0,10,2) # The last variable indicates 
                    # the quantity of numbers of sequence

array([ 0., 10.])

<b> How do I create a random sequence?

In [55]:
np.random.rand(5) # From 0 to 1 - equal probability - Uniform Distribution

array([0.60434686, 0.09766259, 0.93700551, 0.19965751, 0.81824349])

In [56]:
np.random.rand(1)

array([0.13931048])

In [57]:
np.random.rand(2,2)

array([[0.73223145, 0.831719  ],
       [0.30068261, 0.05637445]])

In [58]:
np.random.randn(2) # Normal Distribution

array([-0.53882409, -0.73679882])

In [59]:
np.random.randint(0,100,10) # From 0 to 100 and number quantity

array([30, 34, 78, 51, 26, 28, 33, 77, 29, 95])

<b> How do I reshape an array? (Array to Matrix)

In [60]:
a = np.random.rand(25) # array 
a

array([0.27451687, 0.52097878, 0.58242766, 0.29399453, 0.33873696,
       0.2792495 , 0.61343983, 0.36308214, 0.93768416, 0.70323286,
       0.28914091, 0.01541393, 0.16097221, 0.22771949, 0.02658472,
       0.74680233, 0.52669745, 0.10129304, 0.75726711, 0.22048723,
       0.54310002, 0.75648476, 0.35557797, 0.50635206, 0.33892312])

In [61]:
m = a.reshape(5,5) # matrix
m

array([[0.27451687, 0.52097878, 0.58242766, 0.29399453, 0.33873696],
       [0.2792495 , 0.61343983, 0.36308214, 0.93768416, 0.70323286],
       [0.28914091, 0.01541393, 0.16097221, 0.22771949, 0.02658472],
       [0.74680233, 0.52669745, 0.10129304, 0.75726711, 0.22048723],
       [0.54310002, 0.75648476, 0.35557797, 0.50635206, 0.33892312]])

In [62]:
m.shape

(5, 5)

In [63]:
m.min()

0.015413925502768988

In [64]:
m.max()

0.9376841647614924

<b> How to do indexation?

In [65]:
a[3]

0.2939945277384183

In [66]:
a[3:5]

array([0.29399453, 0.33873696])

In [67]:
a[:5]

array([0.27451687, 0.52097878, 0.58242766, 0.29399453, 0.33873696])

In [68]:
a[3:]

array([0.29399453, 0.33873696, 0.2792495 , 0.61343983, 0.36308214,
       0.93768416, 0.70323286, 0.28914091, 0.01541393, 0.16097221,
       0.22771949, 0.02658472, 0.74680233, 0.52669745, 0.10129304,
       0.75726711, 0.22048723, 0.54310002, 0.75648476, 0.35557797,
       0.50635206, 0.33892312])

In [69]:
m

array([[0.27451687, 0.52097878, 0.58242766, 0.29399453, 0.33873696],
       [0.2792495 , 0.61343983, 0.36308214, 0.93768416, 0.70323286],
       [0.28914091, 0.01541393, 0.16097221, 0.22771949, 0.02658472],
       [0.74680233, 0.52669745, 0.10129304, 0.75726711, 0.22048723],
       [0.54310002, 0.75648476, 0.35557797, 0.50635206, 0.33892312]])

In [70]:
m[1:2,3:] # lines and columns 

array([[0.93768416, 0.70323286]])

In [71]:
bol = m>0.5
m[bol]

array([0.52097878, 0.58242766, 0.61343983, 0.93768416, 0.70323286,
       0.74680233, 0.52669745, 0.75726711, 0.54310002, 0.75648476,
       0.50635206])

<b> Slice

In [72]:
a2 = a[:3].copy()
a2

array([0.27451687, 0.52097878, 0.58242766])

<b> Operations

In [73]:
a3 = np.arange(0,11)
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
a3 + a3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [75]:
a3 * a3

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [76]:
a3/a3

<ipython-input-76-99999762a85a>:1: RuntimeWarning: invalid value encountered in true_divide
  a3/a3


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [77]:
a3 + 10 # all of elements

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [78]:
np.sqrt(a3)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [79]:
np.exp(a3)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [80]:
np.mean(a3)

5.0

In [81]:
np.std(a3)

3.1622776601683795

In [82]:
np.sin(a3)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [83]:
a3.max()

10

In [84]:
a3.min()

0

<b> Solving Systems of Linear Equations

In [91]:
# 4x + 0y + 0z = 96
# -3x + 8y + 3z = 192
# 0x + 0y + 12z = 96

# A.X = B

A = np.array([[4,0,0],[-3,8,3],[0,0,12]])
# X = [x,y,z]
B = np.array([96,192,96])

inv_A = np.linalg.inv(A) # Inverse Matrix
X = inv_A.dot(B)
X

array([24., 30.,  8.])

<b> Eigenpairs of matrix

In [95]:
autovalue,autovector = np.linalg.eig(A)
print(autovalue)

[ 8.  4. 12.]


In [96]:
print(autovector)

[[0.  0.8 0. ]
 [1.  0.6 0.6]
 [0.  0.  0.8]]


<b> Variance

In [100]:
data = [2.75,1.75,1.25,0.25]
ardata = np.array(data)
np.var(ardata)

0.8125